Debug: false
Statistics: true
DeathMessages:
   enabled: true
   includeDeathCount: true
Worlds:
 - world
MySQL:
   enable: true
   host: localhost
   port: 3306
   user: DeathPain
   password: password
   database: deathpain
Version: 0