DeathMessages:
   enabled: true
   includeDeathCount: true
Respawning:
   handleRespawns: true
   respawnPoint:
       - world:
       - x:
       - y:
       - z:
Punishments:
   enable: true
   interval: 30
   perInterval: -1
   intervalWhileOffline: false
   death: 2
   revengeKill: -2
   normalKill: -1
Worlds:
   - world
MySQL:
   enable: true
   host: localhost
   port: 3306
   user: DeathPain
   password: password
   database: deathpain
Version: 0
Debug: false