name: DeathPain
main: me.igwb.DeathPain.Plugin
version: 0.1
commands:
   death:
      description: Lists a death ranking.
      usage:  /death top
      permission: death.top
      permission-message: You don't have permission to use this command!